apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:hIKPR3h4RRsZyVuZiiOfyVWBq9TudbH8d+GhqlWb84UgrF34NT8OOw==,iv:kBqhy7to8TVY5bJqH6TUZKheO6xvAmxHPk9TBx9DDMY=,tag:Sb4FUEmthHANgFyAm0pFmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nmen5wfgu4lzdxerlag2vcthch9pnr4ysd5k60p75ydplfs3rd2sdl2yts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVURVT2lkRzJQQW1YbGNU
            bXZ0YmIxVyttQVFvT3ZaS2NNNytNeVlLTHdrCklTK2RSYXhYYUdVQ0gvaUd5bFJZ
            STlIOWN3Yk0vQUV0TEdIT0VUdXk2T2cKLS0tIFRsR0dCcFZqNlRjSDdmRVUrdXpI
            QXN6MU9paHBzNmtoeE52N0QxNzlvWVkKuekG23Awuy2mKgQXjucEt/sbz8H4KBPs
            rR060RqqEk9jGNSwlxx5t5caBONVfwB8cmy0a5Rk6xrGatMwSG3ZFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T19:58:41Z"
    mac: ENC[AES256_GCM,data:9kMXoOUZ/MpHftGxYFaMmpSoFoq7fRd0RgvJvXUmqP079MjMll04mJEAzqPguc+LDxplbG0Pu+RJTG1ykk3Xj4mcyl05c1sEzPgxKHRHH5ymit4VRavqbCWP9Eor2rnOKx+kzJieoAMUZvxbk9pP7EI5Pwd3Zit+T21R61Cvc20=,iv:3XaAdDJot95BZBFFGzXx8X4v6M5plI9QXBDP4lPPPbY=,tag:vGyctBjeR31v14NfpumyAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
