apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:uY5kDlTPXF/6G0st6cxl1/Yp,iv:xhJaAaYYbO8lQM/5IV3ha2+JaHz9eJpLeHcgtS0rH4o=,tag:CKB7OqQCNk50bdGqEirGwA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:u1h+v6GaTkYaJpRDm3cZvem9uOSGjRha1vWxavRNNVimQLw0,iv:qNiAuMIIit7eUlOcr8AaTa5NNXreHLUxbns86hNfaj8=,tag:DUZwy672XvSVp7Ove5M6tg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:+u/1MfVnilenEGcjdYM=,iv:jPeGcIkox5dmAuBXlINIt9UiWwQftAJwFvZmbpeVY70=,tag:BaCw5S0JTAKF2lrrOJexRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nmen5wfgu4lzdxerlag2vcthch9pnr4ysd5k60p75ydplfs3rd2sdl2yts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWDRmSVZVN0xrdHZtK29Y
            dE9nME9RZXF4RWV1K2NSTmhJV3ovMXllYkJBCmtxNmtVMjN5OWtBN2hydDJMQXRa
            UUlzMlc1WldQYnJyTTR5aW5vcGIyV3cKLS0tIDhxV1hNcVRxVm9IbFA0QmRXSjg1
            TXArd2dKUWlrVlMwOFk2WjgzMkZsVTQKkHAw9W4ZiIuorTM9MiCkpF3wsKXJ881z
            9NlclApJ0t8DEkDlydOA6AFTbeC0Kef2MdLMa3Gbzh10A7sPz8xqOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T19:58:40Z"
    mac: ENC[AES256_GCM,data:km1sOFWkwhuQSKCIMgdEr6hruu49K2xM3I77YaRouEuWCUhkAOTiZM5VocwwH0zSEufhgzhAvLKEfOhS+plkAYg8LSOTpTCxuFqlzufrpwN4tazO0etvulUWxza1IV3SrXnD5XoN3w8Mq0yfsQ3k6vjpVV2vLSE7C1FjvCUi4jk=,iv:uf5158HsSLpJn7eJhkO66TacKQvv6W1ETwFp0sYG2Ok=,tag:HMfSjDfq0aEwCoLlaliCLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
