apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:YGgRj2zMlQuBe/CQPpYTH22ZhDIgKnF8pqq9WGHERWS2tFO5,iv:zEumyJclcevvEkXhMia+D5Co/91LzWGMV8ZyWgJrIEw=,tag:CKgZn5K321oxLfQC1qTnWg==,type:str]
    credentials.json: ENC[AES256_GCM,data:eT1Ep/bG14SIVEqyVLiQTK0Zcz6aE217lb9niZ8m2k3UXeZFszivsa/KZZN9oXV07vM80f17HV6PmPWiWfqjSAqZonKI3BFs35xHFPpGK6dcQrE9HDmQEv1g5Wp9VB8YJe1WwGhMEwtvCHcNomUOFUm+aLvkda1lh+PeFgMKmzIcVelckDmp9YDpG86ROKtYkUd7Q6//8qVnkUjWHd8z6JtKp2Z5nJDbJdFkTIS7PA==,iv:aP6sOgKEZzzCIaPFYXWOaZTn5WWSfIHGbBggUXafy4U=,tag:hMXzrc/13011yKEBwQhhfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nmen5wfgu4lzdxerlag2vcthch9pnr4ysd5k60p75ydplfs3rd2sdl2yts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWTJOcGJGTjNSZ0NncU1o
            dFZVS2VkZjBJYzBqV3ZXNTJHREh0WGpUelRzCnljKzdGNHM2Sy9VNEpuZEpJNVdj
            RFZBa084aUdpbm80MW9TYVBDeGpaWTQKLS0tIGJyRm1nR3FxWUxqSHBtc2YyakZX
            anFXcEdLVTR0OUZ3aUczaHNUQWViVjQKPeJ+7wU7TAYmOZ6Ba4N1C/Ww5X9q210P
            RMc3UqsywHg7GbhTOUTx5ZeyrdQZD3CVoyp2G34JTsvmrEjIx0ZO5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-05T19:58:40Z"
    mac: ENC[AES256_GCM,data:exf5z+KfY9TGkR1/amJe+4p1wMWA3UZbGrZSX7zJsHNiqrJHQ5IA9k7B6k5YECcKKY/pUltEH+h2AullDTY0UIh8giwDEDXQaRfbTJA7IcH04arP0GTWjekzNAA42JH4jdc7AZREsFfgwfueLT8MnZ9OsFAMIE0a9rVRKi0ZwsE=,iv:z64XDu2sRbnO3Uz+mDXANBrWiSPLXVnhr2Imh4w+jdM=,tag:WJotkNQQnhaTHIAwR98btQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
